apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paper-server
  namespace: argocd
spec:
  project: default
  source:
    # Replace <YOUR_GITHUB_USERNAME>. Example: <YOUR_GITHUB_USERNAME> becomes Xata.
    repoURL: https://github.com/Xata/msud-cmute-gitops-workshop.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: paper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true